/**
 * Proactive Watcher Ontology
 *
 * Defines the schemas for proactive suggestions generated by the watcher.
 */

import type { OntologySchema } from '../../core/ontology/types.js';

export const proactiveWatcherOntology: OntologySchema = {
  id: 'trellis:proactive-watcher',
  name: 'Proactive Watcher Schema',
  description: 'Schema for proactive agent suggestions',
  version: '1.0.0',
  entities: [
    {
      name: 'AgentSuggestion',
      description: 'A proactive suggestion generated by an agent observing the graph',
      attributes: [
        { name: 'title', type: 'string', required: true },
        { name: 'description', type: 'string', required: true },
        {
          name: 'status',
          type: 'string',
          enum: ['pending', 'accepted', 'rejected', 'dismissed'],
          required: true,
        },
        {
          name: 'type',
          type: 'string',
          description: 'Category of suggestion (e.g. task_proposal, documentation, refactor, config)',
          required: true,
        },
        {
          name: 'confidence',
          type: 'number',
          description: 'Confidence score from 0.0 to 1.0',
        },
        {
          name: 'proposedAction',
          type: 'string',
          description: 'JSON serialized action payload representing what to do if accepted',
        },
        { name: 'createdAt', type: 'string', required: true },
      ],
    },
  ],
  relations: [
    {
      name: 'suggestsFor',
      sourceTypes: ['AgentSuggestion'],
      targetTypes: ['Any'], // Can point to any entity that triggered the suggestion
      description: 'The entity this suggestion is about',
    },
    {
      name: 'generatedByRule',
      sourceTypes: ['AgentSuggestion'],
      targetTypes: ['Any'],
      description: 'The rule or agent definition that triggered this suggestion',
    },
  ],
};
